# Generated by Django 5.1.7 on 2025-03-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarketPlace', '0003_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
