# Generated by Django 5.1.6 on 2025-03-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verfication_document',
            field=models.FileField(blank=True, null=True, upload_to='verfication_documents/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default/default.png', upload_to='profile_pictures/'),
        ),
    ]
