# Generated by Django 5.1.6 on 2025-03-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='unread_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
