# Generated by Django 5.1.6 on 2025-03-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_verfication_document_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_pictures/'),
        ),
    ]
