# Generated by Django 5.1.6 on 2025-03-27 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_user_private_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onetoonemessage',
            old_name='is_document_present',
            new_name='is_attachment_present',
        ),
        migrations.RemoveField(
            model_name='onetoonemessage',
            name='document',
        ),
        migrations.RemoveField(
            model_name='onetoonemessage',
            name='encryption_iv',
        ),
        migrations.AddField(
            model_name='onetoonemessage',
            name='is_message_present',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='OneToOneAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='one_to_one_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conservation_attachments', to='Users.onetooneconversation')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onetoonemessage_attachments', to='Users.onetoonemessage')),
            ],
        ),
        migrations.AddField(
            model_name='onetoonemessage',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_message', to='Users.onetooneattachment'),
        ),
    ]
