# Generated by Django 5.1.6 on 2025-03-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_delete_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetoonemessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
