# Generated by Django 5.1.6 on 2025-03-27 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_rename_is_document_present_onetoonemessage_is_attachment_present_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessages',
            name='is_attachment_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessages',
            name='is_message_present',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='GroupAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='one_to_one_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_attachments', to='Users.group')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_message_attachments', to='Users.groupmessages')),
            ],
        ),
        migrations.AddField(
            model_name='groupmessages',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_attachment_message', to='Users.groupattachment'),
        ),
    ]
