# Generated by Django 5.1.6 on 2025-03-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_onetoonemessage_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetoonemessage',
            name='encryption_iv',
        ),
    ]
