# Generated by Django 5.1.7 on 2025-03-20 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_friendship'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnetoOneConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_aes_key_for_user_a', models.BinaryField()),
                ('encrypted_aes_key_for_user_b', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friendship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='Users.friendship')),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_a', to='Users.user')),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_b', to='Users.user')),
            ],
        ),
        migrations.CreateModel(
            name='OnetoOneMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_message_content', models.BinaryField()),
                ('encryption_iv', models.BinaryField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Users.onetooneconversation')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_onetoone_messages', to='Users.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_onetoone_messages', to='Users.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='onetooneconversation',
            constraint=models.UniqueConstraint(fields=('user_a', 'user_b'), name='unique_onetoone_conversation'),
        ),
    ]
