# Generated by Django 5.1.6 on 2025-03-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_onetoonemessage_encryption_iv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='private_key_encoded',
            new_name='private_key',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='public_key_encoded',
            new_name='public_key',
        ),
    ]
