# Generated by Django 5.1.6 on 2025-03-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_rename_private_key_encoded_user_private_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetoonemessage',
            name='encryption_iv',
            field=models.BinaryField(default=1),
        ),
    ]
