# Generated by Django 5.1.6 on 2025-03-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_onetoonemessage_encryption_iv'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetoonemessage',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='one_to_one_documents/'),
        ),
        migrations.AddField(
            model_name='onetoonemessage',
            name='is_document_present',
            field=models.BooleanField(default=False),
        ),
    ]
